SUPABASE_URL = "https://qlzhfxxxgteuzvkqetin.supabase.co"
SUPABASE_ANON_KEY = "sb_secret_fbyVtQmHShSReMtbaA-fzQ_0VGNAQLm"
CARTO_API_KEY = "cb1_28o4_1_f8fa590c1c61e4bbbaa5d95d"
#DO NOT UPDATE KEYS ON THIS FILE, USE THE STREAMLIT SECRETS SETTINGS"
